version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      DB_SOURCE: postgresql://user:password@db:5432/todo_db?sslmode=disable
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres-data:
