// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package persistence

import (
	"database/sql"
)

type Todo struct {
	ID          int32        `json:"id"`
	UserID      int32        `json:"user_id"`
	Title       string       `json:"title"`
	DueDate     sql.NullTime `json:"due_date"`
	Priority    int32        `json:"priority"`
	IsCompleted bool         `json:"is_completed"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type User struct {
	ID           int32        `json:"id"`
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}
