// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package persistence

import (
	"context"
)

type Querier interface {
	CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteTodo(ctx context.Context, arg DeleteTodoParams) error
	GetTodo(ctx context.Context, id int32) (Todo, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListTodos(ctx context.Context, userID int32) ([]Todo, error)
	// ソート機能付きリスト取得
	ListTodosWithSort(ctx context.Context, arg ListTodosWithSortParams) ([]Todo, error)
	// 完了切り替え専用クエリ
	ToggleTodoComplete(ctx context.Context, arg ToggleTodoCompleteParams) (Todo, error)
	UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
